//
//  EnumComponent.swift
//  Fonts
//
//  Created by J on 2/20/17.
//  Copyright © 2017 Chan Choon Hee. All rights reserved.
//

import Foundation



enum components : String{
    case achievement = "achievement"
    case activityBarTime = "activityBarTime"
    case activityHours = "activityHours"
    case activityTime = "activityTime"
    case activityType = "activityType"
    case activityTypeAppr = "activityTypeAppr"
    case activityTypeApprIcon = "activityTypeApprIcon"
    case activityTypeField = "activityTypeField"
    case activityTypeFieldIcon = "activityTypeFieldIcon"
    case activityTypeFieldIconHm = "activityTypeFieldIconHm"
    case activityTypeNone = "activityTypeNone"
    case activityTypeNoneIcon = "activityTypeNoneIcon"
    case activityTypeOffice = "activityTypeOffice"
    case activityTypeOfficeIcon = "activityTypeOfficeIcon"
    case activityTypeOfficeIconHm = "activityTypeOfficeIconHm"
    case addAppr = "addAppr"
    case addApptBtn = "addApptBtn"
    case addContPhoto = "addContPhoto"
    case addCustomLabelBtn = "addCustomLabelBtn"
    case apprBtn = "apprBtn"
    case apprCont = "apprCont"
    case apprContHmNR = "apprContHmNR"
    case apprContHmR = "apprContHmR"
    case apprContAddToList = "apprContAddToList"
    case apprContNum = "apprContNum"
    case apprContNumNR = "apprContNumNR"
    case apprContNumR = "apprContNumR"
    case apprContSn = "apprContSn"
    case apprContSnHm = "apprContSnHm"
    case apprContSnHmNR = "apprContSnHmNR"
    case apprContSnHmR = "apprContSnHmR"
    case apprContStatus = "apprContStatus"
    case apprDate = "apprDate"
    case apprDetails = "apprDetails"
    case apprEditBtn = "apprEditBtn"
    case apprText = "apprText"
    case apprTitle = "apprTitle"
    case apptApprNotes = "apptApprNotes"
    case apptApprNotesDate = "apptApprNotesDate"
    case apptPrompt = "apptPrompt"
    case apptPromptDone = "apptPromptDone"
    case apptBtn = "apptBtn"
    case apptContSn = "apptContSn"
    case apptDetails = "apptDetails"
    case apptDetailsDone = "apptDetailsDone"
    case apptText = "apptText"
    case apptTitle = "apptTitle"
    case apptTitleDone = "apptTitleDone"
    case backBtn = "backBtn"
    case callstatusOption = "callstatusOption"
    case cancelBtn = "cancelBtn"
    case cdarDate = "cdarDate"
    case cdarDay = "cdarDay"
    case cdarTitle = "cdarTitle"
    case chartData = "chartData"
    case columnBtn = "columnBtn"
    case columnTop = "columnTop"
    case contBtn = "contBtn"
    case contListDetails = "contListDetails"
    case contName = "contName"
    case contSn = "contSn"
    case contTitle = "contTitle"
    case dailyRecPrivateNotes = "dailyRecPrivateNotes"
    case dailyRecPublicNotes = "dailyRecPublicNotes"
    case dailyRecRemarks = "dailyRecRemarks"
    case dailyRecSBA = "dailyRecSBA"
    case dailyRecSteps = "dailyRecSteps"
    case dailyRecStepsDesc = "dailyRecStepsDesc"
    case dayDateMonth = "dayDateMonth"
    case dismissBtn = "dismissBtn"
    case displayDate = "displayDate"
    case displayDay = "displayDay"
    case doneBtn = "doneBtn"
    case editBtn = "editBtn"
    case exportExcelBtn = "exportExcelBtn"
    case formDate = "formDate"
    case formDetails = "formDetails"
    case formFillDetails = "formFillDetails"
    case formFillPlaceholder = "formFillPlaceholder"
    case formNotesDate = "formNotesDate"
    case formSetDetailsBtn = "formSetDetailsBtn"
    case graphAxisX = "graphAxisX"
    case graphAxisY = "graphAxisY"
    case graphLegend = "graphLegend"
    case groupNameCBox = "groupNameCBox"
    case highlightMemberBtn = "highlightMemberBtn"
    case importBtn = "importBtn"
    case initialsBar = "initialsBar"
    case leftTitle = "leftTitle"
    case listDetails = "listDetails"
    case moduleTitle = "moduleTitle"
    case monthYearWeek = "monthYearWeek"
    case moreOptionsBtn = "moreOptionsBtn"
    case notesLoadMoreBtn = "notesLoadMoreBtn"
    case pendingAppr = "pendingAppr"
    case pendingApptPromptBtn = "pendingApptPromptBtn"
    case pendingApptPromptMsg = "pendingApptPromptMsg"
    case pendingTaskSubTitle = "pendingTaskSubTitle"
    case pendingTaskTitle = "pendingTaskTitle"
    case purposeBtn = "purposeBtn"
    case recBtn = "recBtn"
    case recText = "recText"
    case recTime = "recTime"
    case recTitle = "recTitle"
    case recTotalHours = "recTotalHours"
    case recTotalWork = "recTotalWork"
    case referral = "referral"
    case removeContBtn = "removeContBtn"
    case reportDate = "reportDate"
    case reportSubTabs = "reportSubTabs"
    case reportTabs = "reportTabs"
    case rescheduleApprBtn = "rescheduleApprBtn"
    case rescheduleConfirmationBtn = "rescheduleConfirmationBtn"
    case rightTitle = "rightTitle"
    case searchBar = "searchBar"
    case selectBtn = "selectBtn"
    case selectMobileBtn = "selectMobileBtn"
    case selectCountryCodeBtn = "selectCountryCodeBtn"
    case setPrimaryBtn = "setPrimaryBtn"
    case sortbyCBox = "sortbyCBox"
    case subTitle = "subTitle"
    case title = "title"
    case todayBtn = "todayBtn"
    case updateBtn = "updateBtn"
    case weeklyAchievement = "weeklyAchievement"
    case weeklyGoal = "weeklyGoal"
    
  
}
