//
//  EnumComponent.swift
//  Fonts
//
//  Created by J on 2/20/17.
//  Copyright © 2017 Chan Choon Hee. All rights reserved.
//

import Foundation

class enumComponent {
    
    enum components {
        case achievement
        case activityBarTime
        case activityHours
        case activityTime
        case activityType
        case activityTypeAppr
        case activityTypeApprIcon
        case activityTypeField
        case activityTypeFieldIcon
        case activityTypeFieldIconHm
        case activityTypeNone
        case activityTypeNoneIcon
        case activityTypeOffice
        case activityTypeOfficeIcon
        case activityTypeOfficeIconHm
        case addAppr
        case addApptBtn
        case addContPhoto
        case addCustomLabelBtn
        case apprBtn
        case apprCont
        case apprContHmNR
        case apprContHmR
        case apprContAddToList
        case apprContNum
        case apprContNumNR
        case apprContNumR
        case apprContSn
        case apprContSnHm
        case apprContSnHmNR
        case apprContSnHmR
        case apprContStatus
        case apprDate
        case apprDetails
        case apprEditBtn
        case apprText
        case apprTitle
        case apptApprNotes
        case apptApprNotesDate
        case apptPrompt
        case apptPromptDone
        case apptBtn
        case apptContSn
        case apptDetails
        case apptDetailsDone
        case apptText
        case apptTitle
        case apptTitleDone
        case backBtn
        case callstatusOption
        case cancelBtn
        case cdarDate
        case cdarDay
        case cdarTitle
        case chartData
        case columnBtn
        case columnTop
        case contBtn
        case contListDetails
        case contName
        case contSn
        case contTitle
        case dailyRecPrivateNotes
        case dailyRecPublicNotes
        case dailyRecRemarks
        case dailyRecSBA
        case dailyRecSteps
        case dailyRecStepsDesc
        case dayDateMonth
        case dismissBtn
        case displayDate
        case displayDay
        case doneBtn
        case editBtn
        case exportExcelBtn
        case formDate
        case formDetails
        case formFillDetails
        case formFillPlaceholder
        case formNotesDate
        case formSetDetailsBtn
        case graphAxisX
        case graphAxisY
        case graphLegend
        case groupNameCBox
        case highlightMemberBtn
        case importBtn
        case initialsBar
        case leftTitle
        case listDetails
        case moduleTitle
        case monthYearWeek
        case moreOptionsBtn
        case notesLoadMoreBtn
        case pendingAppr
        case pendingApptPromptBtn
        case pendingApptPromptMsg
        case pendingTaskSubTitle
        case pendingTaskTitle
        case purposeBtn
        case recBtn
        case recText
        case recTime
        case recTitle
        case recTotalHours
        case recTotalWork
        case referral
        case removeContBtn
        case reportDate
        case reportSubTabs
        case reportTabs
        case rescheduleApprBtn
        case rescheduleConfirmationBtn
        case rightTitle
        case searchBar
        case selectBtn
        case selectMobileBtn
        case selectCountryCodeBtn
        case setPrimaryBtn
        case sortbyCBox
        case subTitle
        case title
        case todayBtn
        case updateBtn
        case weeklyAchievement
        case weeklyGoal
    }
    
    func component (_ componentName: components ) -> String {
        switch componentName {
        case .achievement:
            return "achievement"
        case .activityBarTime:
            return "activityBarTime"
        case .activityHours:
            return "activityHours"
        case .activityTime:
            return "activityTime"
        case .activityType:
            return "activityType"
        case .activityTypeAppr:
            return "activityTypeAppr"
        case  .activityTypeApprIcon:
            return "activityTypeApprIcon"
        case .activityTypeField:
            return "activityTypeField"
        case .activityTypeFieldIcon:
            return "activityTypeFieldIcon"
        case .activityTypeFieldIconHm:
            return "activityTypeFieldIconHm"
        case .activityTypeNone:
            return "activityTypeNone"
        case .activityTypeNoneIcon:
            return "activityTypeNoneIcon"
        case .activityTypeOffice:
            return "activityTypeOffice"
        case .activityTypeOfficeIcon:
            return "activityTypeOfficeIcon"
        case .activityTypeOfficeIconHm:
            return "activityTypeOfficeIconHm"
        case .addAppr:
            return "addAppr"
        case .addApptBtn:
            return "addApptBtn"
        case .addContPhoto:
            return "addContPhoto"
        case .addCustomLabelBtn:
            return "addCustomLabelBtn"
        case .apprBtn:
            return "apprBtn"
        case .apprCont:
            return "apprCont"
        case .apprContHmNR:
            return "apprContHmNR"
        case .apprContHmR:
            return "apprContHmR"
        case .apprContAddToList:
            return "apprContAddToList"
        case .apprContNum:
            return "apprContNum"
        case .apprContNumNR:
            return "apprContNumNR"
        case .apprContNumR:
            return "apprContNumR"
        case .apprContSn:
            return "apprContSn"
        case .apprContSnHm:
            return "apprContSnHm"
        case  .apprContSnHmNR:
            return "apprContSnHmNR"
        case .apprContSnHmR:
            return "apprContSnHmR"
        case .apprContStatus:
            return "apprContStatus"
        case .apprDate:
            return "apprDate"
        case .apprDetails:
            return "apprDetails"
        case .apprEditBtn:
            return "apprEditBtn"
        case .apprText:
            return "apprText"
        case .apprTitle:
            return "apprTitle"
        case .apptApprNotes:
            return "apptApprNotes"
        case .apptApprNotesDate:
            return "apptApprNotesDate"
        case .apptPrompt:
            return "apptPrompt"
        case .apptPromptDone:
            return "apptPromptDone"
        case .apptBtn:
            return "apptBtn"
        case .apptContSn:
            return "apptContSn"
        case .apptDetails:
            return "apptDetails"
        case .apptDetailsDone:
            return "apptDetailsDone"
        case .apptText:
            return "apptText"
        case .apptTitle:
            return "apptTitle"
        case .apptTitleDone:
            return "apptTitleDone"
        case .backBtn:
            return "backBtn"
        case .callstatusOption:
            return "callstatusOption"
        case .cancelBtn:
            return "cancelBtn"
        case .cdarDate:
            return "cdarDate"
        case .cdarDay:
            return "cdarDay"
        case .cdarTitle:
            return "cdarTitle"
        case .chartData:
            return "chartDate"
        case .columnBtn:
            return "columnBtn"
        case .columnTop:
            return "columnTop"
        case .contBtn:
            return "contBtn"
        case .contListDetails:
            return "contListDetails"
        case .contName:
            return "contName"
        case .contSn:
            return "contSn"
        case .contTitle:
            return "contTitle"
        case .dailyRecPrivateNotes:
            return "dailyRecPrivateNotes"
        case .dailyRecPublicNotes:
            return "dailyRecPublicNotes"
        case .dailyRecRemarks:
            return "dailyRecRemarks"
        case .dailyRecSBA:
            return "dailyRecSBA"
        case .dailyRecSteps:
            return "dailyRecSteps"
        case .dailyRecStepsDesc:
            return "dailyRecStepsDesc"
        case .dayDateMonth:
            return "dayDateMonth"
        case .dismissBtn:
            return "dismissBtn"
        case .displayDate:
            return "displayDate"
        case .displayDay:
            return "displayDay"
        case .doneBtn:
            return "doneBtn"
        case .editBtn:
            return "editBtn"
        case .exportExcelBtn:
            return "exportExcelBtn"
        case .formDate:
            return "formDate"
        case .formDetails:
            return "formDetails"
        case .formFillDetails:
            return "formFillDetails"
        case .formFillPlaceholder:
            return "formFillPlaceholder"
        case .formNotesDate:
            return "formNotesDate"
        case .formSetDetailsBtn:
            return "formSetDetailsBtn"
        case .graphAxisX:
            return "graphAxisX"
        case .graphAxisY:
            return "graphAxisY"
        case .graphLegend:
            return "graphLegend"
        case .groupNameCBox:
            return "groupNameCbox"
        case .highlightMemberBtn:
            return "highlightMemberBtn"
        case .importBtn:
            return "importBtn"
        case .initialsBar:
            return "initialBar"
        case .leftTitle:
            return "leftTitle"
        case .listDetails:
            return "listDetails"
        case .moduleTitle:
            return "moduleTitle"
        case .monthYearWeek:
            return "monthYearWeek"
        case .moreOptionsBtn:
            return "moreOptionsBtn"
        case .notesLoadMoreBtn:
            return "notesLoadMoreBtn"
        case .pendingAppr:
            return "pendingAppr"
        case .pendingApptPromptBtn:
            return "pendingApptPromptBtn"
        case .pendingApptPromptMsg:
            return "pendingApptPromptMsg"
        case .pendingTaskSubTitle:
            return "pendingTaskSubTitle"
        case .pendingTaskTitle:
            return "pendingTaskTitle"
        case .purposeBtn:
            return "purposeBtn"
        case .recBtn:
            return "recBtn"
        case .recText:
            return "recText"
        case .recTime:
            return "recTime"
        case .recTitle:
            return "recTitle"
        case .recTotalHours:
            return "recTotalHours"
        case .recTotalWork:
            return "recTotalWork"
        case .referral:
            return "referral"
        case .removeContBtn:
            return "removeContBtn"
        case .reportDate:
            return "reportDate"
        case .reportSubTabs:
            return "reportSubTabs"
        case .reportTabs:
            return "reportTabs"
        case .rescheduleApprBtn:
            return "rescheduleApprBtn"
        case .rescheduleConfirmationBtn:
            return "rescheduleConfirmationBtn"
        case .rightTitle:
            return "rightTitle"
        case .searchBar:
            return "searchBar"
        case .selectBtn:
            return "selectBtn"
        case .selectMobileBtn:
            return "selectMobileBtn"
        case .selectCountryCodeBtn:
            return "selectCountryCodeBtn"
        case .setPrimaryBtn:
            return "setPrimaryBtn"
        case .sortbyCBox:
            return "sortbyCBox"
        case .subTitle:
            return "subTitle"
        case .title:
            return "title"
        case .todayBtn:
            return "todayBtn"
        case .updateBtn:
            return "updateBtn"
        case .weeklyAchievement:
            return "weeklyAchievement"
        case .weeklyGoal:
            return "weeklyGoal"
        }
    }
}
